{
 "title": "System Health Metrics",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(node_uname_info,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Disk",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - avg(irate(node_cpu_seconds_total{mode=\"idle\", job=\"$job\"}[5m])) by (instance) * 100\n\n",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Available Disk Space",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{mountpoint=\"/\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{job=\"$job\"} - node_memory_MemFree_bytes{job=\"$job\"}) / node_memory_MemTotal_bytes{job=\"$job\"}) * 100\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Used Disk Space",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\"}  - node_filesystem_free_bytes{mountpoint=\"/\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RAM Overview",
   "type": "stat",
   "gridPos": { "h": 16, "w": 13, "x": 5, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"$job\"}",
     "legendFormat": "Total RAM for {{instance}}"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{job=\"$job\"} - node_memory_MemAvailable_bytes{job=\"$job\"})\n",
     "legendFormat": "Used RAM for {{instance}}"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{job=\"$job\"}\n",
     "legendFormat": "Available RAM for {{instance}}"
    }
   ]
  }
 ]
}