{
 "title": "Directory Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "directory_targets",
    "label": "directory:",
    "query": {
     "query": "label_values(up{job=\"directory_monitor\"}, directory)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Files Added in Each 5 Mins Interval",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "files_added_last_5_minutes{directory=\"$directory_targets\"}",
     "legendFormat": "{{directory}}"
    }
   ]
  },
  {
   "title": "Trend of Files Added Today",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "files_added_today{directory=\"$directory_targets\"}",
     "legendFormat": "{{directory}}"
    }
   ]
  },
  {
   "title": "Files Added in Last 5 mins",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "files_added_last_5_minutes{directory=\"$directory_targets\"}",
     "legendFormat": "{{directory}}"
    }
   ]
  },
  {
   "title": "Files Added Today",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "files_added_today{directory=\"$directory_targets\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Trend of File Sizes Today",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "size_of_files_today{directory=\"$directory_targets\"}",
     "legendFormat": "{{directory}}"
    }
   ]
  },
  {
   "title": "Size of Files Added Today",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "size_of_files_today{directory=\"$directory_targets\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}