-- Collapse Opex Consolidate SQL Queries
--id from 1
INSERT INTO collapsible_items (id,name, created_at, updated_at)
VALUES

(1, 'Personnel',NOW(), NOW()),
(2, 'Communication',NOW(), NOW()),
(3, 'Achat d''énergie - Bâtiment - Gardiennage',NOW(), NOW()),
(4, 'Lignes et réseaux (entretien & achats)',NOW(), NOW()),
(5, 'Fees du contrat GMNS',NOW(), NOW()),
(6, 'Matériel de transport (Entretien et locat°)',NOW(), NOW()),
(7, 'Maintenance  informatique',NOW(), NOW()),
(8, 'Frais d''achats d''études, honoraires',NOW(), NOW()),
(9, 'Management fees',NOW(), NOW()),
(10, 'Transport, déplacement, mission ',NOW(), NOW()),
(11, 'Frais postaux, bancaires et assurances',NOW(), NOW()),
(12, 'Achats de mat. et fournitures consom.',NOW(), NOW()),
(13, 'Redevances régulateur',NOW(), NOW()),
(14, 'Droits sur le trafic International Entrant',NOW(), NOW()),
(15, 'Autres impôts et taxes',NOW(), NOW()),
(16, 'Prov. R&C',NOW(), NOW());

--id from 1
INSERT INTO collapse_types (id,collapsible_item_id, name, sequence_id, created_at, updated_at)
VALUES

-- collapsible_item_id: 1
(1, 1, 'TAXES SUR APPOINTEMENTS ET SAL', 10, NOW(), NOW()),
(2, 1, 'APPOINTEMENTS, SALAIRES PERSON', 20, NOW(), NOW()),
(3, 1, 'CONGES PAYES PERSONNEL NATIONA', 30, NOW(), NOW()),
(4, 1, 'CHARGES SOCIALES S/ REMUNERATI', 40, NOW(), NOW()),
(5, 1, 'AUTRES CHARGES SOCIALES', 50, NOW(), NOW()),
(6, 1, 'PERSONNEL INTERIMAIRE & STAGIA', 60, NOW(), NOW()),
(7, 1, 'PRIMES ET GRATIFICATIONS PERSO', 70, NOW(), NOW()),
(8, 1, 'INDEMNITES DE LICENCIEMENT PER', 80, NOW(), NOW()),
(9, 1, 'EAU RESIDENCES', 90, NOW(), NOW()),
(10, 1, 'ELECTRICITE RESIDENCES', 100, NOW(), NOW()),
(11, 1, 'LOYERS RESIDENCES', 110, NOW(), NOW()),
(12, 1, 'ENTRETIEN ET REPARATIONS RESID', 120, NOW(), NOW()),
(13, 1, 'FRAIS MEDICAUX PERSONNEL NATIO', 130, NOW(), NOW()),
(14, 1, 'AVANTAGES EN NATURE PERSONNEL', 140, NOW(), NOW()),
(15, 1, 'TRANSFERT DE CHARGES D''EXPLOITATION', 150, NOW(), NOW()),
(16, 1, 'EAU RESIDENCES', 160, NOW(), NOW()),
(17, 1, 'ELECTRICITE RESIDENCES', 170, NOW(), NOW()),
(18, 1, 'LOYERS RESIDENCES', 180, NOW(), NOW()),
(19, 1, 'ENTRETIEN ET REPARATIONS RESID', 190, NOW(), NOW()),
(20, 1, 'FRAIS DE TELEPHONE RESIDENCES', 200, NOW(), NOW()),
(21, 1, 'PRIMES ET GRATIFICATIONS PERSO', 210, NOW(), NOW()),
(22, 1, 'INDEMNITES DE LICENCIEMENT PER', 220, NOW(), NOW()),
(23, 1, 'AVANTAGES EN NATURE PERSONNEL', 230, NOW(), NOW()),
(24, 1, 'AUTRES INDEMNITES ET AVANTAGES', 240, NOW(), NOW()),
(25, 1, 'FRAIS DE FORMATION DU PERSONNE', 250, NOW(), NOW()),
(26, 1, 'TRANSPORT PERSONNEL', 260, NOW(), NOW()),
(27, 1, 'RECEPTIONS PERSONNEL', 270, NOW(), NOW()),
(28, 1, 'ASSURANCE DU PERSONNEL', 280, NOW(), NOW()),
(29, 1, 'Réduction budget', 290, NOW(), NOW()),

-- collapsible_item_id: 2
(30, 2, 'VARIATION DE STOCKS AUTRES APPRO', 10, NOW(), NOW()),
(31, 2, 'ANNONCES, INSERTIONS TELE', 20, NOW(), NOW()),
(32, 2, 'ANNONCES, INSERTIONS RADIO', 30, NOW(), NOW()),
(33, 2, 'ANNONCES, INSERTIONS PRESSE', 40, NOW(), NOW()),
(34, 2, 'FRAIS D''AGENCES PUBLICITAIRES', 50, NOW(), NOW()),
(35, 2, 'CONCEPTIONS, PRODUCTION PUBLIC', 60, NOW(), NOW()),
(36, 2, 'CATALOGUES, IMPRIMES PUBLICITA', 70, NOW(), NOW()),
(37, 2, 'ENSEIGNES PUBLICITAIRES - AFFI', 80, NOW(), NOW()),
(38, 2, 'FOIRES ET EXPOSITIONS', 90, NOW(), NOW()),
(39, 2, 'CADEAUX A LA CLIENTELE', 100, NOW(), NOW()),
(40, 2, 'FRAIS DE COLLOQUES, SEMINAIRES', 110, NOW(), NOW()),
(41, 2, 'RELATIONS PUBLIQUES', 120, NOW(), NOW()),
(42, 2, 'DEVELOPPEMENT DE LA MARQUE', 130, NOW(), NOW()),
(43, 2, 'AUTRES IMPOTS ET TAXES DIRECTS', 140, NOW(), NOW()),
(44, 2, 'ENQUETES ET ETUDES DE MARCHES', 150, NOW(), NOW()),

-- collapsible_item_id: 3
(45, 3, 'LOYERS ENTREPOTS', 10, NOW(), NOW()),
(46, 3, 'ELECTRICITE CT AKASSATO', 20, NOW(), NOW()),
(47, 3, 'EAU CT', 30, NOW(), NOW()),
(48, 3, 'ELECTRICITE SITES TECHNIQUES', 40, NOW(), NOW()),
(49, 3, 'ELECTRICITE SITES TECHNIQUES C', 50, NOW(), NOW()),
(50, 3, 'VARIATION DE STOCKS, CARBURANT', 60, NOW(), NOW()),
(51, 3, 'FRAIS DE CARBURANT ET LUBRIFIA', 70, NOW(), NOW()),
(52, 3, 'LOYERS SITES TECHNIQUES', 80, NOW(), NOW()),
(53, 3, 'FRAIS DE GARDIENNAGE', 90, NOW(), NOW()),
(54, 3, 'LOYERS SIEGE ET AGENCES', 100, NOW(), NOW()),
(55, 3, 'FOURNITURES D''ENTRETIEN NON ST', 110, NOW(), NOW()),
(56, 3, 'ENTRETIEN ET REPARATIONS BATS', 120, NOW(), NOW()),
(57, 3, 'FRAIS DE GARDIENNAGE', 130, NOW(), NOW()),
(58, 3, 'EAU BUREAUX, ADMINISTRATION, C', 140, NOW(), NOW()),
(59, 3, 'ELECTRICITE BUREAUX, ADMINISTR', 150, NOW(), NOW()),
(60, 3, 'FRAIS DE TELEPHONE BUREAUX', 160, NOW(), NOW()),
(61, 3, 'FRAIS DE TELECOPIE', 170, NOW(), NOW()),
(62, 3, 'AUTRES FRAIS DE COMMUNICATIONS', 180, NOW(), NOW()),
(63, 3, 'FRAIS CONNEXION INTERNET', 190, NOW(), NOW()),
(64, 3, 'Contrainte :SBEE', 200, NOW(), NOW()),

-- collapsible_item_id: 4
(65, 4, 'ACHATS PETIT MATERIEL ET OUTIL', 10, NOW(), NOW()),
(66, 4, 'ENTRETIEN ET REPARATIONS BATS', 20, NOW(), NOW()),
(67, 4, 'ENTRETIEN ET REPARATIONS SITES', 30, NOW(), NOW()),
(68, 4, 'VARIATION DE STOCKS AUTRES APPRO DT', 40, NOW(), NOW()),
(69, 4, 'ENTRETIEN ET REPARATIONS EQUIP', 50, NOW(), NOW()),
(70, 4, 'MAINTENANCE EQUIPEMENTS TECHNI', 60, NOW(), NOW()),
(71, 4, 'LOYERS D''ESPACES EN CO-LOCATIO', 70, NOW(), NOW()),
(72, 4, 'LOYERS LIAISONS SIGNALISATIONS', 80, NOW(), NOW()),
(73, 4, 'LOYERS LIAISONS SEGMENT SPACIA', 90, NOW(), NOW()),
(74, 4, 'LOYERS LIAISONS MIC', 100, NOW(), NOW()),
(75, 4, 'LOYERS LIAISONS FIBRES OPTIQUE', 110, NOW(), NOW()),
(76, 4, 'LOYERS AUTRES LIAISONS', 120, NOW(), NOW()),
(77, 4, 'LOCATION D''INFRASTRUCTURES TEL', 130, NOW(), NOW()),
(78, 4, 'LOCATION D''EQUIPEMENTS TELECO', 140, NOW(), NOW()),
(79, 4, 'AUTRES LOCATIONS ET CHARGES LO', 150, NOW(), NOW()),
(80, 4, 'REMUNERATIONS TRANSITAIRES', 160, NOW(), NOW()),
(81, 4, 'FRAIS DE DEBOURS ENLEVEMENT', 170, NOW(), NOW()),

-- collapsible_item_id: 5
(82, 5, 'HONORAIRES CONSULTANTS (ERICSSON-GNMS)', 10 , NOW(), NOW()),

-- collapsible_item_id: 6
(83, 6, 'ENTRETIEN ET REPARATIONS VEH. TECHNIQUES', 10, NOW(), NOW()),
(84, 6, 'ENTRETIEN ET REPARATIONS VEH. ADMINISTRATIFS', 20, NOW(), NOW()),
(85, 6, 'ASSURANCE MATERIEL DE TRANSPORT', 30, NOW(), NOW()),
(86, 6, 'ACHATS CARBURANT VEH. ADMIN.', 40, NOW(), NOW()),
(87, 6, 'ACHATS CARBURANT VEH. TECH.', 50, NOW(), NOW()),

-- collapsible_item_id: 7
(88, 7, 'FOURNITURES INFORMATIQUES STOCK', 10, NOW(), NOW()),
(89, 7, 'VARIATION DE STOCKS AUTRES APPRO DSI', 20, NOW(), NOW()),
(90, 7, 'ENTRETIEN MATERIEL INFORMATIQUE', 30, NOW(), NOW()),
(91, 7, 'MAINTENANCE INFORMATIQUE', 40, NOW(), NOW()),

-- collapsible_item_id: 8
(92, 8, 'FRAIS DE RECRUTEMENT DU PERSON & FORMATION', 10, NOW(), NOW()),
(93, 8, 'REMUNERATIONS TRANSITAIRES', 20, NOW(), NOW()),
(94, 8, 'FRAIS DE DEBOURS ENLEVEMENT', 30, NOW(), NOW()),
(95, 8, 'HONORAIRES AVOCATS, HUISSIERS', 40, NOW(), NOW()),
(96, 8, 'HONORAIRES CONSULTANTS', 50, NOW(), NOW()),
(97, 8, 'HONORAIRES CAC', 60, NOW(), NOW()),
(98, 8, 'HONORAIRES AUDITEURS', 70, NOW(), NOW()),
(99, 8, 'HONORAIRES DIVERS', 80, NOW(), NOW()),
(100, 8, 'FRAIS D''ACTES ET DE CONTENTIEU', 90, NOW(), NOW()),
(101, 8, 'TRAVAUX, ACHATS MATERIELS ET EQUIPEMENTS', 100, NOW(), NOW()),
(102, 8, 'FRAIS DE GESTION ROAMING CHAMB', 110, NOW(), NOW()),
(103, 8, 'AUTRES FRAIS DE TRANSPORTS', 120, NOW(), NOW()),
(104, 8, 'ETUDES ET RECHERCHES', 130, NOW(), NOW()),
(105, 8, 'DOCUMENTATION GENERALE', 140, NOW(), NOW()),
(106, 8, 'DOCUMENTATION TECHNIQUE', 150, NOW(), NOW()),
(107, 8, 'DIVERS FRAIS', 160, NOW(), NOW()),
(108, 8, 'REDEVANCES POUR LOGICIELS', 170, NOW(), NOW()),
(109, 8, 'COTISATIONS', 180, NOW(), NOW()),
(110, 8, 'CONCOURS DIVERS', 190, NOW(), NOW()),
(111, 8, 'FRAIS DE DEMENAGEMENT', 200, NOW(), NOW()),
(112, 8, 'DONS', 210, NOW(), NOW()),
(113, 8, 'AUTRES LOCATIONS ET CHARGES LO', 220, NOW(), NOW()),

-- collapsible_item_id: 9
(114, 9, 'MANAGEMENT FEES - FRAIS DE GES', 10, NOW(), NOW()),
(115, 9, 'REDEVANCES POUR MARQUE', 20, NOW(), NOW()),

--collapsible_item_id: 10
(116, 10, 'VOYAGES ET DEPLACEMENTS (Missions)', 10, NOW(), NOW()),
(117, 10, 'VOYAGES ET DEPLACEMENTS (Formations)', 20, NOW(), NOW()),
(118, 10, 'RECEPTIONS PERSONNEL (Autres)', 30, NOW(), NOW()),
(119, 10, 'MISSIONS & FRAIS D''HOTELS PERSONNEL (Missions)', 40, NOW(), NOW()),
(120, 10, 'MISSIONS & FRAIS D''HOTELS PERSONNEL (Formations)', 50, NOW(), NOW()),
(121, 10, 'TRANSPORT VISITEURS', 60, NOW(), NOW()),
(122, 10, 'RECEPTIONS VISITEURS & PERSONNEL , DIVERS T', 70, NOW(), NOW()),
(123, 10, 'MISSIONS & FRAIS D''HOTELS VISI', 80, NOW(), NOW()),
(124, 10, 'TRANSPORTS DE PLIS', 90, NOW(), NOW()),
(125, 10, 'FRAIS D''AFFRANCHISSEMENT', 100, NOW(), NOW()),

-- collapsible_item_id: 11
(126, 11, 'ASSURANCE MULTIRISQUES', 10, NOW(), NOW()),
(127, 11, 'ASSURANCE RISQUES D''EXPLOITATI', 20, NOW(), NOW()),
(128, 11, 'ASSURANCE TRANSPORT SUR ACHATS', 30, NOW(), NOW()),
(129, 11, 'AUTRES PRIMES D''ASSURANCE', 40, NOW(), NOW()),
(130, 11, 'FRAIS SUR EFFETS', 50, NOW(), NOW()),
(131, 11, 'FRAIS D''EMISSION D''EMPRUNTS', 60, NOW(), NOW()),
(132, 11, 'AUTRES FRAIS BANCAIRES', 70, NOW(), NOW()),
(133, 11, 'FRAIS DE VIREMENT', 80, NOW(), NOW()),
(134, 11, 'FRAIS D''ARRETES DE COMPTES', 90, NOW(), NOW()),

-- collapsible_item_id: 12
(135, 12, 'FOURNITURES DE BUREAU NON STOC', 10, NOW(), NOW()),
(136, 12, 'ACHATS PETIT MATERIEL ET OUTIL', 20, NOW(), NOW()),
(137, 12, 'Contrainte : Identification', 30, NOW(), NOW()),

--collapsible_item_id: 13
(138, 13, 'REDEVANCES AUTORITE DE REGULATION (Redevance licence & Contribution)', 10, NOW(), NOW()),
(139, 13, 'REDEVANCES AUTORITE DE REGULAT (Redevance Trafic & autres)', 20, NOW(), NOW()),

--collapsible_item_id: 14
(140, 14, 'Droits sur le trafic International Entrant', 10, NOW(), NOW()),

--collapsible_item_id: 15
(141, 15, 'IMPOTS FONCIERS ET TAXES ANNEX', 10, NOW(), NOW()),
(142, 15, 'PATENTES, LICENCES ET TAXES AN', 20, NOW(), NOW()),
(143, 15, 'AUTRES IMPOTS ET TAXES DIRECTS', 30, NOW(), NOW()),
(144, 15, 'IMPOTS ET TAXES INDIRECTS', 40, NOW(), NOW()),
(145, 15, 'TAXES SUR LES VEHICULES DE SOC', 50, NOW(), NOW()),
(146, 15, 'AUTRES DROITS D''ENREGISTREMENT', 60, NOW(), NOW()),
(147, 15, 'AUTRES IMPOTS & TAXES', 70, NOW(), NOW()),
(148, 15, 'PENALITES & AMENDES FISCALES', 80, NOW(), NOW()),

--collapsible_item_id: 16
(149, 16, 'PERTES / CREANCES CLIENTS', 10, NOW(), NOW()),
(150, 16, 'PERTES / AUTRES DEBITEURS', 20, NOW(), NOW()),
(151, 16, 'CHARGES PROVISIONNEES / RISQUE', 30, NOW(), NOW()),
(152, 16, 'CHARGES PROVISIONNEES S/ STOCK', 40, NOW(), NOW()),
(153, 16, 'CHARGES PROVISIONNEES S/ CREAN', 50, NOW(), NOW()),
(154, 16, 'AUTRES CHARGES PROVISIONNEES', 60, NOW(), NOW()),
(155, 16, 'REPRISES PROVISIONS S/ RISQUES', 70, NOW(), NOW()),
(156, 16, 'REPRISES PROV. POUR RISQUES &', 80, NOW(), NOW()),
(157, 16, 'REPRISES PROVISIONS POUR DEPRE', 90, NOW(), NOW()),
(158, 16, 'REPRISES AUTRES CHARGES PROVIS', 100, NOW(), NOW()),
(159, 16, 'REPRISES PROV. POUR GROSSES RE', 110, NOW(), NOW());
