[ddp]
localhost
13.234.6.83
15.206.52.115
15.206.97.207
3.7.50.219

[all:vars]
#default values
host_key_checking=false
ansible_ssh_private_key_file=./Digiwise.pem
ask_pass=false
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_user=ec2-user

#default previleges
ansible_become=true
ansible_become_user=root